### PR TITLE
FIXED BRANCH FOR NJK 😩

### LINKED ISSUE #93: [Feature] Implement Non-Functional MVP UI
- [ ] Add a link on the Internal Tools home page to a new Cabin Sorting Page in the UI directory
- [ ] Implement these Figma Designs https://www.figma.com/file/Ur8DMCmxLx7WMKqHoEChR3/Cabin-Sorting?type=design&node-id=0-1&t=90Ya7y9T2r7UjUdw-0 in the UI directory
- [ ] Be sure to use the [mui](https://mui.com/) elements for the buttons and empty table
- [ ] There should be no functionality

### PR DESCRIPTION
**Pull request by mike10911**
Fixed #93 
- Added a link on the Internal Tools home page to a new Cabin Sorting Page in the UI directory
- Implemented these Figma Designs https://www.figma.com/file/Ur8DMCmxLx7WMKqHoEChR3/Cabin-Sorting?type=design&node-id=0-1&t=90Ya7y9T2r7UjUdw-0 in the UI directory
-  Didn't include functionality, only worked on design
Screen Shot 2023-06-17 at 7 56 00 PM

Screen Shot 2023-06-17 at 7 55 49 PM

### CODE REVIEW

File: ui/components/csvTable/CSVCabinTable.tsx [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+  const cabinValues = {
+    Cabin1: ['email1-1', 'email1-2'],
+    Cabin2: ['email2-1', 'email2-2', 'email2-3'],
+    Cabin3: ['email3-1', 'email3-2'],
+    Cabin4: ['email4-1', 'email4-2'],
+    Cabin5: [],
+    Cabin6: ['email6-1', 'email6-2']
+  }
+
+  // making rows of data
```
Comment (mike10911) [inline ui/components/csvTable/CSVCabinTable.tsx:30]: Remove comments in this file

File: ui/components/csvTable/CSVCabinTable.tsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+  })
+
+  return (
+    <>
+      <TableContainer component={Paper} elevation={0}>
+        <Table aria-label="simple table">
+          <TableHead>
+            <StyledTableHeader>
+              {headerNames.map((header: any) => (
+                <TableCell key="key" sx={{ border: '1px solid #B9B9B9' }}>
```
Comment (mike10911) [inline ui/components/csvTable/CSVCabinTable.tsx:46]: change key to nanoid

File: ui/components/csvTable/CSVCabinTable.tsx [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+                  {header}
+                </TableCell>
+              ))}
+            </StyledTableHeader>
+          </TableHead>
+          <TableBody>
+            {rows.map((row) => (
+              <TableRow key={nanoid()}>
+                {Object.keys(cabinValues).map((cabin, cabinIndex) => (
+                  <TableCell key="key" align="left" sx={{ border: '1px solid #B9B9B9' }}>
```
Comment (mike10911) [inline ui/components/csvTable/CSVCabinTable.tsx:56]: change key to nanoid

**Review by mike10911 — COMMENTED** [review]
OMG THIS IS SOO GOOD. GREAT WORK PICKING UP MUI SO QUICKLY!!!! Just a few small changes bc it is so freaking good!

- We want to match the designs as close as possible. The corners should be flush to reflect the design
current:
Screen Shot 2023-06-20 at 7 10 52 PM
Goal:
Screen Shot 2023-06-20 at 7 12 01 PM

- To match the design, can we take some padding away from the cells
Goal
Screen Shot 2023-06-20 at 7 13 43 PM

**Comment by mike10911** [comment]
Also, there are some new eslint errors!

**Review by Mandy-cyber — APPROVED** [review]
LGTM party ppl!

**Review by hackbeanbot — APPROVED** [review]
New changes look great!. Good to merge after Eslint fixes!
